# Site
repository: vicky-mao/vicky-mao.github.io
# favicon: images/favicon.ico

# Personal info
name: 毛艺桦
title: 高级咨询师
email: 522631185@qq.com
website: https://vicky-mao.github.io/vicky-mao-lite-cn

# Social links
#twitter_username: facespics
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: vicky-mao-6ab988138
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  您好，我是一名战略规划咨询师，在中观经济研究领域拥有丰富经验，曾经为多家企业、政府机构及非营利组织提供战略规划服务，帮助他们在政策制定、产业规划、土地及政务服务领域取得重要进展及显著成果。
  您好，我是一名战略规划咨询师，在中观经济研究领域拥有丰富经验，曾经为多家企业、政府机构及非营利组织提供战略规划服务，帮助他们在政策制定、产业规划、土地及政务服务领域取得重要进展及显著成果。

  Hi there, my name’s Vicky and I’m a senior consultant in meso-economy arena. I have got rich experience in laying out strategic plans for quite a number of types of projects including policy, industrialization, land & civil issues, etc., providing intellectual support for corporations, governments and NGOs.

  Projects I worked on covered a wide range of topics, from strategy to operations. In a typical engagement, I own a work stream to deliver the end recommendation. Typical activities involve performing analysis of the particular problems as defined for the work stream, including identifying and prioritizing issues for further analysis, synthesizing the insights from the analyses, developing recommendations based on the synthesis, and creating plans to implement the recommendations.

  I am most skilled in <mark>quantitative</mark>, <mark>analytical</mark> and <mark>conceptual</mark> problem-solving.

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
#more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my career as a corporate strategy consultant, I'm also happy wife of an intelligent man and proud mom of two cute kids. My family is the strongest support behind my success and certainly one of the most important part of my life.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
